### PR TITLE
Helping readers by adding Light/Dark theme option

### PR DESCRIPTION
**Pull request by qubydev**

### CODE REVIEW

**Review by Mabi19 — CHANGES_REQUESTED** [review]
I have a couple of remarks:
- The theme toggler's code should be in template.html, not content.html (it's definitely not content!)
- The table zebra striping's high contrast is quite jarring IMO. It should be a lot more subtle.
- The light theme's component backgrounds look quite ugly. In general, I want to use colour sparingly in light theme (although I think that the highlighting selections are fine).
- In dark theme, links (both visited and non-visited) are hard to read.
- The selection colours are very nice.
- The bit underlines' colour-coding is broken.
- It seems like you're also trying to set the coloured bits' backgrounds. I don't really want this; I don't think it looks good and chose to reserve backgrounds for virtual bits.
- The theme should be saved across page reloads and the initial theme should be set by the user's preference (you can get this via media query).
- Please use 4-space indents for consistency with the rest of the codebase. (It also seems like you've autoformatted the CSS file, but I'm fine with that)

**Comment by qubydev** [comment]
> I have a couple of remarks:
> 
> * The theme toggler's code should be in template.html, not content.html (it's definitely not content!)
> * The table zebra striping's high contrast is quite jarring IMO. It should be a lot more subtle.
> * The light theme's component backgrounds look quite ugly. In general, I want to use colour sparingly in light theme (although I think that the highlighting selections are fine).
> * In dark theme, links (both visited and non-visited) are hard to read.
> * The selection colours are very nice.
> * The bit underlines' colour-coding is broken.
> * It seems like you're also trying to set the coloured bits' backgrounds. I don't really want this; I don't think it looks good and chose to reserve backgrounds for virtual bits.
> * The theme should be saved across page reloads and the initial theme should be set by the user's preference (you can get this via media query).
> * Please use 4-space indents for consistency with the rest of the codebase. (It also seems like you've autoformatted the CSS file, but I'm fine with that)

Hi there,

I appreciate your feedback and the detailed points you've made.

1. Modifying...
2. Modifying... (I share a similar perspective)
3. The color palette was originally inspired by an older book theme, but I agree with your suggestion that, in the Light theme, aligning the component's background color closely with the body background with some adjustments would enhance its appearance. (I'd love to hear your thoughts on the Dark theme as well.) Modifying...
4. I had the exact same impression after following the link. Modifying...
5. Thank you!
6. I'm not quite clear on this point.
7. Agreed, I'll make the necessary modifications. (Should I leave it as it was?)
8. I'm fully aware of this; I was planning to implement it after receiving feedback. Modifying...
9. The formatting was primarily based on a VS Code extension; I'll make sure to take care of this.

**Comment by Mabi19** [comment]
You seem to have transpiled (?) the build tooling for some reason.
Please also clean up your temporarily commented out code.

Also, please try to write meaningful commit messages. Reviewing PRs like this isn't very fun.

I have only one styling remark: the buttons in dark mode are weird.
- The icons shouldn't be dark gray, but text color
- They should, in general, look similar to the radio selectors (so, `--border` border and `--accent` background when hovered; in light mode the color should change to `whitesmoke` when hovered; although, thinking about it, transitioning the filter might be hard - I'd be okay with removing the transition in this case)

Anyway, as for the undecided dark mode colours:
- Unvisited links: `#519ce8`
- Visited links: `#a879d7`
- Component border: `#3a5160`
- Virtual bit backgrounds: `#444444`

**Comment by qubydev** [comment]
I am **really really sorry** . 
It was a mistaken review clicked. My plan was to discuss anything I want in the issue section first then after cleaning up everything, I was supposed to make a review request.
However, somehow I made a review request mistakenly without noticing, I apologize for that. and I will make sure to fix build tools before any update.
Also thank you for the remarks !

**Comment by qubydev** [comment]
Hi !
Can you have a look at the dark mode button hover. I guess they still kinda odd. Well, what do you think ?
visit: https://malay77patra.github.io/numbers/

**Comment by Mabi19** [comment]
The icons now seem to be the right colour, but the hover is very much white.
I already specified how I want them to look, but here it is again:
> They should, in general, look similar to the radio selectors (so, --border border and, when hovered, --accent background; in light mode the text color should change to `whitesmoke` when hovered, although, thinking about it, transitioning the filter might be hard - I'd be okay with removing the transition in this case)

**Pull request closed without merging**
